name: Create Output from Issue

on: 
  issues: 
    types: opened

permissions:
  contents: write
  pull-requests: write

jobs:
  create-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Confiigure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Create branch
        run: |
          BRANCH_NAME="output-${{ github.event.issue.number }}"
          git checkout -b $BRANCH_NAME

      - name: Create markdown file
        run: |
          TITLE="${{ github.event.issue.title }}"
          FILE_NAME=$(echo "$TITLE" | sed 's/\[Output\] //g' | tr  " " "-" | tr '[:upper:]' '[:lower:]')
          mkdir -p contents/knowledge/misc
          cp 99_template/temp.md contents/knowledge/misc/$FILE_NAME.md

      - name: Commit and Push
        run: |
          ls contents/knowledge/misc
          git add .
          git status
          git commit -m "create: ${{ github.event.issue.title }}"
          git push origin HEAD

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "${{ github.event.issue.title }}" \
            --body "Issueより自動生成" \
            --base main \
            --head "output-${{ github.event.issue.number }}"
